# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:
  schedule:
    - cron: '* */10 * * *' 
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25.1'

    - name: Build
      run: go build -v .

    - name: run
      run: ./subs-check -f ./config/config.yaml

    - name: Commit
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add ./output
        git add output
        git commit -m "collect $(date '+%Y-%m-%d %H:%M:%S')"

    - name: 推送更改
      uses: ad-m/github-push-action@master
      with:
          #github_token: ${{ secrets.TOKEN }}
          branch: master
          force: true
